import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Hotel } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        <header className="sticky top-0 z-40 bg-white/80 backdrop-blur border-b">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
            <div className="flex items-center gap-2 font-semibold text-blue-700">
              <span className="text-2xl">
                <Hotel />
              </span>
              <span>Hotel Finder</span>
            </div>
            <nav className="hidden sm:flex items-center gap-4 text-sm">
              <Link className="px-3 py-2 rounded-lg hover:bg-gray-100" href="/">
                Home
              </Link>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
